@db_table
Feature: verify CMS DB__0000

  Background:
    * url baseUrl
    * call read('support.feature@common_functions')
    * def apiComponents = envConfig
    * def ArrayList = Java.type('java.util.ArrayList')
    * def Collections = Java.type('java.util.Collections')
    * def DBUtils = Java.type('executables.utils.DBUtils')
    * def db = new DBUtils(apiComponents['DB_url'], apiComponents['DB_username'], apiComponents['DB_password'])

  Scenario Outline: verify DB columns__0000.

    * print "<<<<<<<<<<<<<<<<<< table_name for column verification is >>>>>>>>>>>>>>>", "<table_name>"

    # extracting the column and constraint data from DB
    * def table = db.readRows("SELECT * FROM <table_name> WHERE ROWNUM <= 1")
    * def response_Key = karate.keysOf(table[0])

    # sorting the extracted column list
    * eval Collections.sort(response_Key, java.lang.String.CASE_INSENSITIVE_ORDER)
    * print "<<<<<<<<<<<<Response_Key>>>>>>>>>>", response_Key

    # sorting the expected column list
    * def column_list = <column_list>
    * eval Collections.sort(column_list, java.lang.String.CASE_INSENSITIVE_ORDER)
    * print "<<<<<<<<<<<<Expected_Key>>>>>>>>>>", column_list

    # matching the expected and extracted column list
    * match <column_list> contains response_Key

    Examples:
      |table_name|column_list|
      |COUPON    |["ID","TITLE","DESCRIPTION","DETAILS","CREATE_TS","MERCHANT","STATUS","VALID_FROM","VALID_TO","TERMS","IMAGE_ID","URL","AFFILIATE_URL","NOTE","REDEEM_DAYHOUR","REDEEM_GENDER","REDEEM_MIN_AGE","REDEEM_MAX_AGE","REDEEM_LOCATION","REDEEM_EXEMPT_DATES","DOWNLOAD_CAP","REDEEM_CAP","PRIVATE","COUPON_CODE","REDUCTION_TYPE","AMOUNT_THRESHOLD","REDUCTION","REDUCTION_MAX","DISCOUNT_TYPE","DISCOUNT_EXTRA_RULES","STICKER","WIFI_SSID","VENDOR_CID","BANNER_NAME","BANNER_IMAGE_ID","SHORT_TERM_TYPE","SHORT_TERM_TIME","MERCHANT_GROUP","BRAND","COUPON_TYPE","MAX_REDEEM","SOURCE","BOOST","COUPON_LABEL","REDEEM_COUNT","DISCOUNT_MAX","DISCOUNT_MIN_BILL","DISCOUNT_ABS_VALUE","DISCOUNT_PERCENTAGE_VALUE","USER_GROUP","MERCHANT_REDEEM_CAP","DEMO_COUPON","BLOCK_COUNT","DISCOUNT_COUPON","PER_CART_REDEEM","ENABLEDFORMULTIREDEMPTION"]|

      |CLOSED_LOOP_REDEMPTION|["CANCELLED_QUANTITY","BLOCKED_QUANTITY","ACCEPT_TS","RETURN_UPTO","DELIVERED_TS","RETURN_TS","RELEASE_TS","SETTLING_TS","BUSINESS_TS","BLOCK_TS","TRANSACTION_ID","BATCH_ID","REDEEM_TS","CHECKOUT_TS","CREATE_TS","MASID","STORE_ID","TERMINAL_ID","STATUS","BILL_AMOUNT","DISCOUNT_AMOUNT","COUPON_CODE","CUSTOMER","COUPON","ID","MERCHANT_DISCOUNT_CONTRIBUTION"]|

      |SKU_CONDITION_DATA |["ID","SKU","NAME","QUANTITY","COUPON_CONDITION","ACTUAL_PRICE","SELLING_PRICE","MINIMUM_BILL_VALUE"]|

      |B2B_COUPON     |["VENDOR_CONTRIBUTION","MINIMUM_BILL_VALUE","BILL_CONDITION","ID","B2C_COUPON_ID","CAMPAIGN_ID","CAMPAIGN_TYPE","CONDITIONAL_COUPON_ID","COUPON_TITLE","CREATE_TS","DERIVED_FROM","DISCOUNT_AMOUNT","MASID","MERCHANT_GROUP","MERCHANT_REDEEM_CAP","QUANTITY","REDEEM_COUNT","SKU_ID","SKU_NAME","STATUS","TOTAL_REDEEM_CAP","UPDATE_TS","VALID_FROM","VALID_TO","VENDOR_FUNDING"]|

      |FC_MERCHANT_COUPONS|["HOLD_TS","VENDOR_CONTRIBUTION","MINIMUM_BILL_VALUE","ID","COUPON","COUPON_TITLE","MASID","CUSTOMER_COUPON_CODE","MERCHANT_COUPON_CODE","DISCOUNT_AMOUNT","STATUS","TRANSACTION_ID","CREATE_TS","CHECKOUT_TS","VERIFY_TS","REDEEM_TS","UPDATE_TS","CANCEL_TS","VALID_FROM","VALID_TO","DELIVERED_TS","CAMPAIGN_TYPE","B2B_COUPON_ID","CONDITIONAL_COUPON","DISPLAY_NAME_ID","CATEGORY_ID","SUB_CATEGORY_ID","CAMPAIGN_ID"]|

      |B2B_UNREALIZED_REDEMPTION|["HOLD_TS","VENDOR_CONTRIBUTION","MINIMUM_BILL_VALUE","ID","COUPON","COUPON_TITLE","MASID","CUSTOMER_COUPON_CODE","MERCHANT_COUPON_CODE","DISCOUNT_AMOUNT","STATUS","TRANSACTION_ID","CREATE_TS","CHECKOUT_TS","VERIFY_TS","REDEEM_TS","UPDATE_TS","CANCEL_TS","VALID_FROM","VALID_TO","DELIVERED_TS","CAMPAIGN_TYPE","B2B_COUPON_ID","CONDITIONAL_COUPON","DISPLAY_NAME_ID","CATEGORY_ID","SUB_CATEGORY_ID","CAMPAIGN_ID"]|

      |B2B_REALIZED_REDEMPTION|["HOLD_TS","VENDOR_CONTRIBUTION","MINIMUM_BILL_VALUE","ID","COUPON","COUPON_TITLE","MASID","CUSTOMER_COUPON_CODE","MERCHANT_COUPON_CODE","DISCOUNT_AMOUNT","STATUS","TRANSACTION_ID","CREATE_TS","CHECKOUT_TS","VERIFY_TS","REDEEM_TS","UPDATE_TS","CANCEL_TS","VALID_FROM","VALID_TO","DELIVERED_TS","CAMPAIGN_TYPE","B2B_COUPON_ID","CONDITIONAL_COUPON","DISPLAY_NAME_ID","CATEGORY_ID","SUB_CATEGORY_ID","CAMPAIGN_ID"]|

      |FC_SKU_CONDITION_DATA  |["FC_MERCHANT_COUPON","NAME","QUANTITY","SKU"]|

      |B2B_REALIZED_SKU_CONDITION|["FC_MERCHANT_COUPON","SKU","NAME","QUANTITY"]|

      |B2B_UNREALIZED_SKU_CONDITION|["FC_MERCHANT_COUPON","SKU","NAME","QUANTITY"]|

      |B2B_SEGMENT_COUPON_MAPPING|["B2B_COUPON_ID","SEGMENT"]|

      | B2B_COUPON_REDEMPTION    | ["B2B_COUPON_ID","MASID","QUANTITY"]|

      | VENDOR_FUNDING_DETAIL     |["ID","COUPONID","MERCHANT_CONTRIBUTION","RELIANCE_CONTRIBUTION","BRAND_CONTRIBUTION","UPDATED_TS"]|

      |CAMPAIGN_LINE_ITEM         |["ID","COUPON","COMPOSITE_SEGMENT","CAMPAIGN"]                                                     |

      |CLIENT_TYPE                |["ID", "NAME"]                                                                                      |

      |JOB_DEFINITION             |["ID","NAME","TYPE","EXECUTABLE","REQUEST_METHOD","REQUEST_URL","MAKER_CHECKER_ENABLED"]            |

      |JOB_DETAIL                 |["ID","JOB_DEF_ID","MAKER_USER_ID","UPLOAD_FILE_ID","UPLOAD_FILE_NAME","JOB_STATE_ID","ACTIVE","APPROVER_USER_ID","UPDATED_TS","CREATED_TS","SCHEDULED_TS","OUTPUT_FILE_ID","APPROVER_COMMENT","USER_GROUP","MAKER_USERNAME","APPROVER_USERNAME","ERROR_FILE_ID"]

      |JOB_STATE                  |["ID", "NAME"] |

      |CATEGORY                   |["ID","NAME","IMAGE_ID","PARENT_ID","NEARBY_DISTANCE","RANK","FONT_ICON","FONT_BACKGROUND","DEPTH","CLIENT_TYPE","STATUS"]|

      |B2BCOUPONMAPPING           |["ID","COUPONCODE","CONSTITUENTCOUPONCODE","STATUS","MASID","CREATEDAT","SEQUENCE"]                                        |

      |MERCHANT                   |["ID","NAME","REPRESENTATIVE","STATUS","IMAGE_ID","URL","PHONE","EMAIL","NOTE","TRAITS","CIN","CREATE_TS","VENDOR_MID","VENDOR_NAME","ENTITY_ID","INSTITUTION_ID","USER_GROUP","UPDATE_TS","WORKITEM_STATUS","TEST_MERCHANT","REDEMPTION_SETTLEMENT_STATUS","DEVICE_MAPPED","ACTIVATED_ONCE"]|

      |ADMINISTRATOR              |["ID","FIRST_NAME","LAST_NAME","DESIGNATION","DEPARTMENT","PHONE","OFFICE_PHONE","EMAIL","CREATE_TS","PRIVILEGE","NOTE","STATUS","USER_GROUP"]                                                                                                                                               |

      |CONFIGURATION              |["CONFIG_NAME","CONFIG_VALUE","CREATE_TS"]                                                                                                                                                                                                                                                   |

      | USER_CONS_COLUMNS         |["OWNER","CONSTRAINT_NAME","TABLE_NAME","COLUMN_NAME","POSITION"]                                                                                                                                                                                                                            |

      |MIDMASID                   |["ID","MID","MASID"]                                                                                                                                                                                                                                                                         |

      |MGID_MID_MASID             |["MGID","MID","MASID"]                                                                                                                                                                                                                                                                       |

      |MERCHANT_ADDRESS           |["ID","MERCHANT","BRANCH_CODE","BRANCH_NAME","ADDRESS","LANDMARK","LOCALITY","ZONE","CITY","STATE","PIN","STATUS","LATITUDE","LONGITUDE","L30","L29","L28","L27","L26","L25","L24","L23","L22","L21","L20","L19","L18","L17","L16","L15","L14","L13","L12","L11","CREATE_TS","VENDOR_ADR_ID","SHOP_NUMBER","UPDATE_TS"]|

      |NM_CAMPAIGN_MERCHANTS      |["NEW_MERCHANT_CAMPAIGN","MID","CREATE_TS","CAMPAIGN_B2B_COUPON","GENERATED_B2B_COUPON"]                                                                                                                                                                                                                               |

      |NM_CAMPAIGN_RULES          |["ID","NEW_MERCHANT_CAMPAIGN","MERCHANT_PROPERTY","PROPERTY_VALUE","INCLUDED"]                                                                                                                                                                                                                                         |

      |NEW_MERCHANT_CAMPAIGN      |["ID","CAMPAIGN_CATEGORY","CREATED_AT","UPDATED_AT","VALID_FROM","VALID_TO","VALIDITY_PERIOD"]                                                                                                                                                                                                                         |

      |NM_CAMPAIGN_COUPONS        |["NEW_MERCHANT_CAMPAIGN","B2B_COUPON"]                                                                                                                                                                                                                                                                                 |

      |MERCHANT_GROUP_EXCLUSION_LIST|["ID","MGID","MASID"]                                                                                                                                                                                                                                                                                                |

 #   |AGGREGATE_COUPON_CODE        |[]

      |BRAND                        |["ID","NAME","IMAGE","DESCRIPTION","CREATE_TS","PARENT","EXTERNAL_ID","USER_GROUP","CATALOGUE_ID","COMPANY_ID","BRAND_TYPE","SUPPORTS_BUDGET","UPDATE_TS","STATUS"]                                                                                                                                                  |

      | MERCHANT_PROPERTY_VALUE     |["MERCHANT","MERCHANT_PROPERTY","PROPERTY_VALUE","CREATE_TS","UPDATE_TS"]                                                                                                                                                                                                                                            |

      |VENDOR_FUNDING_HISTORY       |["ID","COUPONID","MERCHANT_CONTRIBUTION","RELIANCE_CONTRIBUTION","BRAND_CONTRIBUTION","VALID_FROM","VALID_TO"]                                                                                                                                                                                                       |

      |COUPON_UPLOAD_LOG            |["ID","USER_ID","UPLOAD_FILE_NAME","DOWNLOAD_FILE_NAME","CREATE_TS"]                                                                                                                                                                                                                                                 |

      |USER_SEGMENT                 |["ID","NAME","CREATE_TS"]                                                                                                                                                                                                                                                                                            |

      |COMPOSITE_SEGMENT            |["ID","OPERATOR","CREATE_TS"]                                                                                                                                                                                                                                                                                        |

      |USER_SEGMENT_OPERAND         |["ID","USER_SEGMENT","PARENT_COMPOSITE_SEGMENT"]                                                                                                                                                                                                                                                                     |

      |COMPOSITE_SEGMENT_OPERAND    |["ID","COMPOSITE_SEGMENT","PARENT_COMPOSITE_SEGMENT"]                                                                                                                                                                                                                                                                |

      |MG_DEFINITION                |["ID","NAME","MERCHANT_GROUP","AUTO_REFRESH","CREATE_TS","UPDATE_TS","TEST_MERCHANT_GROUP","DEVICE_MAPPED"]                                                                                                                                                                                                          |

      |B2B_CAMPAIGN                 |["ID","NAME","START_DATE","END_DATE","CREATE_TS","UPDATE_TS","DISPLAY_NAME_ID","CATEGORY_ID","SUB_CATEGORY_ID","UPDATED_BY"]                                                                                                                                                                                         |

      |DISCOUNT_TYPE                |["ID","NAME"]                                                                                                                                                                                                                                                                                                        |

      |VOUCHER                      |["ID","CATEGORY","CODE","AUTOAPPLICABLE","TYPE","FUNDEDBY","TITLE","VALID_FROM","VALID_TO","STATUS","ACTIVE","MASID","MERCHANT_GROUP","DISCOUNT_AMOUNT","CREATE_TS","MERCHANT_REDEEM_CAP","TOTAL_REDEEM_CAP","DISCOUNT_TYPE","MAX_DISCOUNT","TERMS","REDEEM_COUNT"]                                                  |

      |VOUCHER_CRITERIA             |["ID","TYPE","VALUE","APPLICABLEON"]                                                                                                                                                                                                                                                                                 |

      |VOUCHER_DISCOUNT_CRITERIA    |["ID","DISCOUNT_TYPE","MAX_DISCOUNT","DISCOUNT_VALUE","MIN_BILL_VALUE","VOUCHER_CODE"]                                                                                                                                                                                                                               |

      |VOUCHER_MERCHANT_REDEMPTION  |["VOUCHER_ID","MASID","QUANTITY"]                                                                                                                                                                                                                                                                                    |

      |VOUCHER_REDEMPTION           |["ID","MASID","VOUCHER_CODE","REDEEM_CODE","DISCOUNT_AMOUNT","STATUS","CREATE_TS","CHECKOUT_TS","REDEEM_TS","UPDATE_TS","CANCEL_TS","DELIVERED_TS"]                                                                                                                                                                  |

      |CRITERIA                     |["ID","TYPE","VALUE","APPLICABLEON"]                                                                                                                                                                                                                                                                                 |

      |CRITERIA_TYPE                |["ID","NAME"]                                                                                                                                                                                                                                                                                                        |

      |PROMOTION_CRITERIA           |["PROMOTION_REFERENCE","CRITERIA","CRITERIA_VALUE"]                                                                                                                                                                                                                                                                  |

      |PROMOTION                    |["ID","REFERENCE","NAME","TYPE","STACKABLE","PRIORITY","ACTIVE","VALID_FROM","VALID_TO","CREATE_TS","UPDATE_TS","DISCOUNT_TYPE","DISCOUNT_VALUE","MAX_DISCOUNT_AMOUNT"]                                                                                                                                              |

      |PROMOTION_TYPE               |["ID","NAME"]                                                                                                                                                                                                                                                                                                        |

      |B2B_DISCOUNT_MAPPING         |["B2B_COUPON_ID","DISCOUNT_TYPE","VALUE","MAX_DISCOUNT"]                                                                                                                                                                                                                                                             |

      |MAS_COPY_LOG                 |["ID","STATUS","START_TS","END_TS","CREATE_FAILED_COUNT","CREATED_COUNT","UPDATE_COUNT","UPDATE_FAILED_COUNT"]                                                                                                                                                                                                       |

      |JPM_MERCHANT_COHORT          |["ID","JPMCOHORTID","CREATEDAT","UPDATEDAT"]                                                                                                                                                                                                                                                                         |

      |MERCHANT_GROUP               |["ID","NAME","DESCRIPTION","CREATE_TS","STATUS","MERCHANT_COUNT","USER_GROUP"]                                                                                                                                                                                                                                       |

      |MERCHANTCOUPONACTIVITY       |["MERCHANTID","LASTUPDATEDAT"]                                                                                                                                                                                                                                                                                       |

      |FC_DATA_MOVEMENT_LOG         |["ID","UPDATE_TS","SCAN_UPTO_ID"]                                                                                                                                                                                                                                                                                    |

      |FC_DATA_MOVEMENT_REDEEMED_LOG|["ID","UPDATE_TS","SCAN_UPTO_ID"]                                                                                                                                                                                                                                                                                    |

      |CAMPAIGN                     |["ID","NAME","PAUSED","START_TIME","END_TIME","CREATE_TS","USER_GROUP"]                                                                                                                                                                                                                                              |

  Scenario Outline: verification DB constraints__0000.
    # extracting the column and constraint data from DB
    * print "<<<<<<<<<<<<<<<<<< table_name for constraint verification is >>>>>>>>>>>>>>>", "<table_name>"
    * def table = db.readRows("SELECT USER_CONS_COLUMNS.COLUMN_NAME, USER_CONSTRAINTS.CONSTRAINT_TYPE FROM USER_CONSTRAINTS INNER JOIN USER_CONS_COLUMNS ON USER_CONSTRAINTS.CONSTRAINT_NAME = USER_CONS_COLUMNS.CONSTRAINT_NAME WHERE USER_CONS_COLUMNS.TABLE_NAME IN (\'" +"<table_name>"+ "\')")
    * print "<<<<<<<<<<<<Response_Key>>>>>>>>>>", table

    # Extracting the column name from the DB data and sorted them
    * def column_name = $table[*].COLUMN_NAME
    * eval Collections.sort(column_name, java.lang.String.CASE_INSENSITIVE_ORDER)
    * print "<<<<<<<<<<<<Response_Key1>>>>>>>>>>", column_name

    # Expected column and constraints
    * def constraint_type_and_column = <constraint_type_and_column>
    * print "<<<<<<<<<<<<Expected_Key>>>>>>>>>>", constraint_type_and_column

    # Extracted the column name from the DB data and sorted them
    * def respective_columns = $constraint_type_and_column[*].COLUMN_NAME
    * eval Collections.sort(respective_columns, java.lang.String.CASE_INSENSITIVE_ORDER)
    * print "<<<<<<<<<<<<Expected_Key1>>>>>>>>>>", respective_columns

    # matching the column and constraints one by one
    * match <constraint_type_and_column> contains deep table

    Examples:
      |table_name|constraint_type_and_column|
      |COUPON|[{"COLUMN_NAME":"REDUCTION_TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VALID_FROM","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VALID_TO","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDEEM_MIN_AGE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDEEM_MAX_AGE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDUCTION_TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"AMOUNT_THRESHOLD","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDUCTION","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDUCTION_TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDUCTION","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"MERCHANT","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"DISCOUNT_TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"DISCOUNT_EXTRA_RULES","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"STICKER","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"BRAND","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"COUPON_TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"TITLE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"DESCRIPTION","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COUPON_TYPE","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VALID_FROM","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VALID_TO","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"TERMS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDEEM_DAYHOUR","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDEEM_GENDER","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDEEM_MIN_AGE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDEEM_MAX_AGE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDEEM_LOCATION","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"PRIVATE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COUPON_CODE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDUCTION_TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"AMOUNT_THRESHOLD","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"IMAGE_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"URL","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"AFFILIATE_URL","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDEEM_DAYHOUR","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDEEM_GENDER","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDEEM_LOCATION","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"PRIVATE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COUPON_CODE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"WIFI_SSID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MERCHANT_GROUP","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"DISCOUNT_COUPON","CONSTRAINT_TYPE":"C"}]|

      |CLOSED_LOOP_REDEMPTION|[{"COLUMN_NAME":"CUSTOMER","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COUPON_CODE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"DISCOUNT_AMOUNT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CHECKOUT_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"COUPON","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"TRANSACTION_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COUPON","CONSTRAINT_TYPE":"C"}]|

      |SKU_CONDITION_DATA |[{"COLUMN_NAME":"MINIMUM_BILL_VALUE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"SKU","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"QUANTITY","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COUPON_CONDITION","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"COUPON_CONDITION","CONSTRAINT_TYPE":"R"}]|

      |B2B_COUPON|[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"QUANTITY","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"SKU_NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"SKU_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"DISCOUNT_AMOUNT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COUPON_TITLE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"MERCHANT_GROUP","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"CAMPAIGN_ID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"CAMPAIGN_TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"}]|

      |FC_MERCHANT_COUPONS|[{"COLUMN_NAME":"HOLD_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COUPON_TITLE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MERCHANT_COUPON_CODE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"DISCOUNT_AMOUNT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"TRANSACTION_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPDATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CAMPAIGN_TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"COUPON","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"B2B_COUPON_ID","CONSTRAINT_TYPE":"R"}]|

      |B2B_UNREALIZED_REDEMPTION|[{"COLUMN_NAME":"HOLD_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COUPON_TITLE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MERCHANT_COUPON_CODE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"DISCOUNT_AMOUNT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"TRANSACTION_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPDATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CAMPAIGN_TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"R"}]|

      |B2B_REALIZED_REDEMPTION|[{"COLUMN_NAME":"HOLD_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COUPON_TITLE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MERCHANT_COUPON_CODE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"DISCOUNT_AMOUNT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"TRANSACTION_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPDATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CAMPAIGN_TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"R"}]|

      |FC_SKU_CONDITION_DATA  |[{"COLUMN_NAME":"FC_MERCHANT_COUPON","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"QUANTITY","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"SKU","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"FC_MERCHANT_COUPON","CONSTRAINT_TYPE":"R"}]|

      |B2B_REALIZED_SKU_CONDITION|[{"COLUMN_NAME":"SKU","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"QUANTITY","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"FC_MERCHANT_COUPON","CONSTRAINT_TYPE":"R"}]|

      |B2B_UNREALIZED_SKU_CONDITION|[{"COLUMN_NAME":"SKU","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"QUANTITY","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"FC_MERCHANT_COUPON","CONSTRAINT_TYPE":"R"}]|

      |B2B_SEGMENT_COUPON_MAPPING|[{"COLUMN_NAME":"SEGMENT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"B2B_COUPON_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"B2B_COUPON_ID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"SEGMENT","CONSTRAINT_TYPE":"U"},{"COLUMN_NAME":"B2B_COUPON_ID","CONSTRAINT_TYPE":"U"}]|

      |B2B_COUPON_REDEMPTION     |[{"COLUMN_NAME":"B2B_COUPON_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"C"},{ "COLUMN_NAME":"B2B_COUPON_ID", "CONSTRAINT_TYPE": "R"},{"COLUMN_NAME":"QUANTITY","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"B2B_COUPON_ID","CONSTRAINT_TYPE":"P"}]|

      |VENDOR_FUNDING_DETAIL     |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COUPONID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MERCHANT_CONTRIBUTION","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"RELIANCE_CONTRIBUTION","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"BRAND_CONTRIBUTION","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPDATED_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"COUPONID","CONSTRAINT_TYPE":"R"}]|

      |CAMPAIGN_LINE_ITEM        |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COUPON","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COMPOSITE_SEGMENT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CAMPAIGN","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"COUPON","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"CAMPAIGN","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"COMPOSITE_SEGMENT","CONSTRAINT_TYPE":"R"}]                        |

      |CLIENT_TYPE               |[{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                          |

      |JOB_DEFINITION            |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REQUEST_METHOD","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REQUEST_URL","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"U"}]                                                                                          |

      |JOB_DETAIL                |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"JOB_DEF_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MAKER_USER_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPLOAD_FILE_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPLOAD_FILE_NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"JOB_STATE_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPDATED_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATED_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"SCHEDULED_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"JOB_DEF_ID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"JOB_STATE_ID","CONSTRAINT_TYPE":"R"}]|

      |JOB_STATE                 |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"U"}]                                                                                                                                                                                                                                                                                                                                                                                                            |

      |CATEGORY                  |[{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NEARBY_DISTANCE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"RANK","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"PARENT_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"PARENT_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                 |

      |B2BCOUPONMAPPING          |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COUPONCODE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CONSTITUENTCOUPONCODE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATEDAT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                      |

      |MERCHANT                  |[{"COLUMN_NAME":"DEVICE_MAPPED","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"PHONE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"EMAIL","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"TRAITS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VENDOR_NAME","CONSTRAINT_TYPE":"U"},{"COLUMN_NAME":"VENDOR_MID","CONSTRAINT_TYPE":"U"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"UPDATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"WORKITEM_STATUS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"TEST_MERCHANT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REDEMPTION_SETTLEMENT_STATUS","CONSTRAINT_TYPE":"C"}]|

      |ADMINISTRATOR             |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"FIRST_NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"LAST_NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"PHONE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"EMAIL","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"PRIVILEGE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"PHONE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"PHONE","CONSTRAINT_TYPE":"U"},{"COLUMN_NAME":"OFFICE_PHONE","CONSTRAINT_TYPE":"U"},{"COLUMN_NAME":"EMAIL","CONSTRAINT_TYPE":"U"}]                                                                                                                                        |

      |CONFIGURATION             |[{"COLUMN_NAME":"CONFIG_NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CONFIG_NAME","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |

      |MIDMASID                  |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"MID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"U"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |

      |MGID_MID_MASID            |[{"COLUMN_NAME":"MGID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MID","CONSTRAINT_TYPE":"C"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |

      |MERCHANT_ADDRESS          |[{"COLUMN_NAME":"UPDATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MERCHANT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ADDRESS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"PIN","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"LATITUDE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"LONGITUDE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L30","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L29","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L28","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L27","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L26","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L25","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L24","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L23","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L22","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L21","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L20","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L19","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L18","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L17","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L16","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L15","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L14","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L13","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L12","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"L11","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"PIN","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"MERCHANT","CONSTRAINT_TYPE":"R"}]|

      |NM_CAMPAIGN_MERCHANTS     |[{"COLUMN_NAME":"NEW_MERCHANT_CAMPAIGN","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NEW_MERCHANT_CAMPAIGN","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"MID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"CAMPAIGN_B2B_COUPON","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"GENERATED_B2B_COUPON","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |

      |NM_CAMPAIGN_RULES         |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NEW_MERCHANT_CAMPAIGN","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MERCHANT_PROPERTY","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"PROPERTY_VALUE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |

      |NEW_MERCHANT_CAMPAIGN      |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CAMPAIGN_CATEGORY","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATED_AT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPDATED_AT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VALID_FROM","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VALID_TO","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VALIDITY_PERIOD","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |

      |NM_CAMPAIGN_COUPONS        |[{"COLUMN_NAME":"NEW_MERCHANT_CAMPAIGN","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"B2B_COUPON","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NEW_MERCHANT_CAMPAIGN","CONSTRAINT_TYPE":"U"},{"COLUMN_NAME":"B2B_COUPON","CONSTRAINT_TYPE":"U"},{"COLUMN_NAME":"NEW_MERCHANT_CAMPAIGN","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"B2B_COUPON","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |

      |MERCHANT_GROUP_EXCLUSION_LIST|[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MGID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |

      |BRAND                        |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"PARENT","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |

      |MERCHANT_PROPERTY_VALUE      |[{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPDATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MERCHANT","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"MERCHANT_PROPERTY","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |

      |VENDOR_FUNDING_HISTORY       |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COUPONID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MERCHANT_CONTRIBUTION","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"RELIANCE_CONTRIBUTION","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"BRAND_CONTRIBUTION","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"COUPONID","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |

      |COUPON_UPLOAD_LOG            |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"USER_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPLOAD_FILE_NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"DOWNLOAD_FILE_NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |

      |USER_SEGMENT                 |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"U"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |

      |COMPOSITE_SEGMENT            |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"OPERATOR","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |

      |USER_SEGMENT_OPERAND         |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"USER_SEGMENT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"PARENT_COMPOSITE_SEGMENT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"USER_SEGMENT","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"PARENT_COMPOSITE_SEGMENT","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |

      |COMPOSITE_SEGMENT_OPERAND    |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"COMPOSITE_SEGMENT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"PARENT_COMPOSITE_SEGMENT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"COMPOSITE_SEGMENT","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"PARENT_COMPOSITE_SEGMENT","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |

      |MG_DEFINITION                |[{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"U"},{"COLUMN_NAME":"DEVICE_MAPPED","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"TEST_MERCHANT_GROUP","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPDATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"MERCHANT_GROUP","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |

      |B2B_CAMPAIGN                 |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPDATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"DISPLAY_NAME_ID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"CATEGORY_ID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"SUB_CATEGORY_ID","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |

      |DISCOUNT_TYPE                |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |

      |VOUCHER                      |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CODE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"AUTOAPPLICABLE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"TITLE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ACTIVE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"DISCOUNT_AMOUNT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"DISCOUNT_TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MAX_DISCOUNT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"MERCHANT_GROUP","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |

      |VOUCHER_CRITERIA             |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VALUE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"APPLICABLEON","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"APPLICABLEON","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"TYPE","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |

      |VOUCHER_DISCOUNT_CRITERIA    |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"DISCOUNT_TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MAX_DISCOUNT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"DISCOUNT_VALUE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MIN_BILL_VALUE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |

      |VOUCHER_MERCHANT_REDEMPTION  |[{"COLUMN_NAME":"VOUCHER_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"QUANTITY","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VOUCHER_ID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |

      |VOUCHER_REDEMPTION           |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VOUCHER_CODE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"MASID","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"STATUS","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |

      |CRITERIA                     |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VALUE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"APPLICABLEON","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |

      |CRITERIA_TYPE                |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |

      |PROMOTION_CRITERIA           |[{"COLUMN_NAME":"CRITERIA_VALUE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CRITERIA","CONSTRAINT_TYPE":"R"},{"COLUMN_NAME":"PROMOTION_REFERENCE","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |

      |PROMOTION                    |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"REFERENCE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"PRIORITY","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VALID_FROM","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VALID_TO","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPDATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"DISCOUNT_VALUE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"REFERENCE","CONSTRAINT_TYPE":"U"},{"COLUMN_NAME":"DISCOUNT_TYPE","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |

      |PROMOTION_TYPE               |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |

      |B2B_DISCOUNT_MAPPING         |[{"COLUMN_NAME":"B2B_COUPON_ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"DISCOUNT_TYPE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"VALUE","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"B2B_COUPON_ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |

      |MAS_COPY_LOG                 |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"START_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |

      |JPM_MERCHANT_COHORT          |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"JPMCOHORTID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"R"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |

      |MERCHANT_GROUP               |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"U"},{"COLUMN_NAME":"NAME","CONSTRAINT_TYPE":"U"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |

      |MERCHANTCOUPONACTIVITY       |[{"COLUMN_NAME":"LASTUPDATEDAT","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"MERCHANTID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |

      |CAMPAIGN                     |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"CREATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |

      |FC_DATA_MOVEMENT_LOG         |[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPDATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |

      |FC_DATA_MOVEMENT_REDEEMED_LOG|[{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"UPDATE_TS","CONSTRAINT_TYPE":"C"},{"COLUMN_NAME":"ID","CONSTRAINT_TYPE":"P"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |